version: 2.1
orbs:
  maven: circleci/maven@1.4.0

workflows:
  workflow:
    jobs:
      - maven/test

dependencies:
  override:
    - mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline

test:
  override:
    - mvn -o surefire:test

deployment:
  main:
    branch: main
    commands:
      - mvn -s .circleci.settings.xml -DskipTests deploy